services:
  client:
    build:
      context: ./client
      target: "development"
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./client/app:/usr/server/app
  play-from-disk-renegotiation:
    build: ./play-from-disk-renegotiation
    ports:
      - "8080:8080"
    volumes:
      - ./play-from-disk-renegotiation:/usr/src/app
    environment:
      TZ: Asia/Tokyo
