services:
  client:
    build:
      context: ./client
      target: "development"
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./client/app:/usr/server/app
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app
    environment:
      TZ: Asia/Tokyo
